// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/Student.proto

package netty.sixexample;

public final class MyDataInfo {
  private MyDataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.text.protobuf.PackType}
   */
  public enum PackType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STUDENT = 0;</code>
     */
    STUDENT(0),
    /**
     * <code>NUMBER = 1;</code>
     */
    NUMBER(1),
    ;

    /**
     * <code>STUDENT = 0;</code>
     */
    public static final int STUDENT_VALUE = 0;
    /**
     * <code>NUMBER = 1;</code>
     */
    public static final int NUMBER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PackType valueOf(int value) {
      return forNumber(value);
    }

    public static PackType forNumber(int value) {
      switch (value) {
        case 0: return STUDENT;
        case 1: return NUMBER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PackType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PackType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PackType>() {
            public PackType findValueByNumber(int number) {
              return PackType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return netty.sixexample.MyDataInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final PackType[] VALUES = values();

    public static PackType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PackType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.text.protobuf.PackType)
  }

  public interface PackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.text.protobuf.Pack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.text.protobuf.PackType packType = 1;</code>
     */
    boolean hasPackType();
    /**
     * <code>required .com.text.protobuf.PackType packType = 1;</code>
     */
    netty.sixexample.MyDataInfo.PackType getPackType();

    /**
     * <code>optional .com.text.protobuf.Student student = 2;</code>
     */
    boolean hasStudent();
    /**
     * <code>optional .com.text.protobuf.Student student = 2;</code>
     */
    netty.sixexample.MyDataInfo.Student getStudent();
    /**
     * <code>optional .com.text.protobuf.Student student = 2;</code>
     */
    netty.sixexample.MyDataInfo.StudentOrBuilder getStudentOrBuilder();

    /**
     * <code>optional .com.text.protobuf.Number number = 3;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional .com.text.protobuf.Number number = 3;</code>
     */
    netty.sixexample.MyDataInfo.Number getNumber();
    /**
     * <code>optional .com.text.protobuf.Number number = 3;</code>
     */
    netty.sixexample.MyDataInfo.NumberOrBuilder getNumberOrBuilder();

    public netty.sixexample.MyDataInfo.Pack.PackCase getPackCase();
  }
  /**
   * Protobuf type {@code com.text.protobuf.Pack}
   */
  public  static final class Pack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.text.protobuf.Pack)
      PackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pack.newBuilder() to construct.
    private Pack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pack() {
      packType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Pack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              netty.sixexample.MyDataInfo.PackType value = netty.sixexample.MyDataInfo.PackType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                packType_ = rawValue;
              }
              break;
            }
            case 18: {
              netty.sixexample.MyDataInfo.Student.Builder subBuilder = null;
              if (packCase_ == 2) {
                subBuilder = ((netty.sixexample.MyDataInfo.Student) pack_).toBuilder();
              }
              pack_ =
                  input.readMessage(netty.sixexample.MyDataInfo.Student.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((netty.sixexample.MyDataInfo.Student) pack_);
                pack_ = subBuilder.buildPartial();
              }
              packCase_ = 2;
              break;
            }
            case 26: {
              netty.sixexample.MyDataInfo.Number.Builder subBuilder = null;
              if (packCase_ == 3) {
                subBuilder = ((netty.sixexample.MyDataInfo.Number) pack_).toBuilder();
              }
              pack_ =
                  input.readMessage(netty.sixexample.MyDataInfo.Number.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((netty.sixexample.MyDataInfo.Number) pack_);
                pack_ = subBuilder.buildPartial();
              }
              packCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Pack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Pack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netty.sixexample.MyDataInfo.Pack.class, netty.sixexample.MyDataInfo.Pack.Builder.class);
    }

    private int bitField0_;
    private int packCase_ = 0;
    private java.lang.Object pack_;
    public enum PackCase
        implements com.google.protobuf.Internal.EnumLite {
      STUDENT(2),
      NUMBER(3),
      PACK_NOT_SET(0);
      private final int value;
      private PackCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PackCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackCase forNumber(int value) {
        switch (value) {
          case 2: return STUDENT;
          case 3: return NUMBER;
          case 0: return PACK_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackCase
    getPackCase() {
      return PackCase.forNumber(
          packCase_);
    }

    public static final int PACKTYPE_FIELD_NUMBER = 1;
    private int packType_;
    /**
     * <code>required .com.text.protobuf.PackType packType = 1;</code>
     */
    public boolean hasPackType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.text.protobuf.PackType packType = 1;</code>
     */
    public netty.sixexample.MyDataInfo.PackType getPackType() {
      @SuppressWarnings("deprecation")
      netty.sixexample.MyDataInfo.PackType result = netty.sixexample.MyDataInfo.PackType.valueOf(packType_);
      return result == null ? netty.sixexample.MyDataInfo.PackType.STUDENT : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.text.protobuf.Student student = 2;</code>
     */
    public boolean hasStudent() {
      return packCase_ == 2;
    }
    /**
     * <code>optional .com.text.protobuf.Student student = 2;</code>
     */
    public netty.sixexample.MyDataInfo.Student getStudent() {
      if (packCase_ == 2) {
         return (netty.sixexample.MyDataInfo.Student) pack_;
      }
      return netty.sixexample.MyDataInfo.Student.getDefaultInstance();
    }
    /**
     * <code>optional .com.text.protobuf.Student student = 2;</code>
     */
    public netty.sixexample.MyDataInfo.StudentOrBuilder getStudentOrBuilder() {
      if (packCase_ == 2) {
         return (netty.sixexample.MyDataInfo.Student) pack_;
      }
      return netty.sixexample.MyDataInfo.Student.getDefaultInstance();
    }

    public static final int NUMBER_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.text.protobuf.Number number = 3;</code>
     */
    public boolean hasNumber() {
      return packCase_ == 3;
    }
    /**
     * <code>optional .com.text.protobuf.Number number = 3;</code>
     */
    public netty.sixexample.MyDataInfo.Number getNumber() {
      if (packCase_ == 3) {
         return (netty.sixexample.MyDataInfo.Number) pack_;
      }
      return netty.sixexample.MyDataInfo.Number.getDefaultInstance();
    }
    /**
     * <code>optional .com.text.protobuf.Number number = 3;</code>
     */
    public netty.sixexample.MyDataInfo.NumberOrBuilder getNumberOrBuilder() {
      if (packCase_ == 3) {
         return (netty.sixexample.MyDataInfo.Number) pack_;
      }
      return netty.sixexample.MyDataInfo.Number.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasStudent()) {
        if (!getStudent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasNumber()) {
        if (!getNumber().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, packType_);
      }
      if (packCase_ == 2) {
        output.writeMessage(2, (netty.sixexample.MyDataInfo.Student) pack_);
      }
      if (packCase_ == 3) {
        output.writeMessage(3, (netty.sixexample.MyDataInfo.Number) pack_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packType_);
      }
      if (packCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (netty.sixexample.MyDataInfo.Student) pack_);
      }
      if (packCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (netty.sixexample.MyDataInfo.Number) pack_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netty.sixexample.MyDataInfo.Pack)) {
        return super.equals(obj);
      }
      netty.sixexample.MyDataInfo.Pack other = (netty.sixexample.MyDataInfo.Pack) obj;

      if (hasPackType() != other.hasPackType()) return false;
      if (hasPackType()) {
        if (packType_ != other.packType_) return false;
      }
      if (!getPackCase().equals(other.getPackCase())) return false;
      switch (packCase_) {
        case 2:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 3:
          if (!getNumber()
              .equals(other.getNumber())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPackType()) {
        hash = (37 * hash) + PACKTYPE_FIELD_NUMBER;
        hash = (53 * hash) + packType_;
      }
      switch (packCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + NUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getNumber().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Pack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Pack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Pack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netty.sixexample.MyDataInfo.Pack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.text.protobuf.Pack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.text.protobuf.Pack)
        netty.sixexample.MyDataInfo.PackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Pack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Pack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netty.sixexample.MyDataInfo.Pack.class, netty.sixexample.MyDataInfo.Pack.Builder.class);
      }

      // Construct using netty.sixexample.MyDataInfo.Pack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        packCase_ = 0;
        pack_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Pack_descriptor;
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Pack getDefaultInstanceForType() {
        return netty.sixexample.MyDataInfo.Pack.getDefaultInstance();
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Pack build() {
        netty.sixexample.MyDataInfo.Pack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Pack buildPartial() {
        netty.sixexample.MyDataInfo.Pack result = new netty.sixexample.MyDataInfo.Pack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packType_ = packType_;
        if (packCase_ == 2) {
          if (studentBuilder_ == null) {
            result.pack_ = pack_;
          } else {
            result.pack_ = studentBuilder_.build();
          }
        }
        if (packCase_ == 3) {
          if (numberBuilder_ == null) {
            result.pack_ = pack_;
          } else {
            result.pack_ = numberBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.packCase_ = packCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netty.sixexample.MyDataInfo.Pack) {
          return mergeFrom((netty.sixexample.MyDataInfo.Pack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netty.sixexample.MyDataInfo.Pack other) {
        if (other == netty.sixexample.MyDataInfo.Pack.getDefaultInstance()) return this;
        if (other.hasPackType()) {
          setPackType(other.getPackType());
        }
        switch (other.getPackCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case NUMBER: {
            mergeNumber(other.getNumber());
            break;
          }
          case PACK_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPackType()) {
          return false;
        }
        if (hasStudent()) {
          if (!getStudent().isInitialized()) {
            return false;
          }
        }
        if (hasNumber()) {
          if (!getNumber().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netty.sixexample.MyDataInfo.Pack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netty.sixexample.MyDataInfo.Pack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packCase_ = 0;
      private java.lang.Object pack_;
      public PackCase
          getPackCase() {
        return PackCase.forNumber(
            packCase_);
      }

      public Builder clearPack() {
        packCase_ = 0;
        pack_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int packType_ = 0;
      /**
       * <code>required .com.text.protobuf.PackType packType = 1;</code>
       */
      public boolean hasPackType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.text.protobuf.PackType packType = 1;</code>
       */
      public netty.sixexample.MyDataInfo.PackType getPackType() {
        @SuppressWarnings("deprecation")
        netty.sixexample.MyDataInfo.PackType result = netty.sixexample.MyDataInfo.PackType.valueOf(packType_);
        return result == null ? netty.sixexample.MyDataInfo.PackType.STUDENT : result;
      }
      /**
       * <code>required .com.text.protobuf.PackType packType = 1;</code>
       */
      public Builder setPackType(netty.sixexample.MyDataInfo.PackType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        packType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.text.protobuf.PackType packType = 1;</code>
       */
      public Builder clearPackType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          netty.sixexample.MyDataInfo.Student, netty.sixexample.MyDataInfo.Student.Builder, netty.sixexample.MyDataInfo.StudentOrBuilder> studentBuilder_;
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public boolean hasStudent() {
        return packCase_ == 2;
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public netty.sixexample.MyDataInfo.Student getStudent() {
        if (studentBuilder_ == null) {
          if (packCase_ == 2) {
            return (netty.sixexample.MyDataInfo.Student) pack_;
          }
          return netty.sixexample.MyDataInfo.Student.getDefaultInstance();
        } else {
          if (packCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return netty.sixexample.MyDataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public Builder setStudent(netty.sixexample.MyDataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pack_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public Builder setStudent(
          netty.sixexample.MyDataInfo.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          pack_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public Builder mergeStudent(netty.sixexample.MyDataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (packCase_ == 2 &&
              pack_ != netty.sixexample.MyDataInfo.Student.getDefaultInstance()) {
            pack_ = netty.sixexample.MyDataInfo.Student.newBuilder((netty.sixexample.MyDataInfo.Student) pack_)
                .mergeFrom(value).buildPartial();
          } else {
            pack_ = value;
          }
          onChanged();
        } else {
          if (packCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (packCase_ == 2) {
            packCase_ = 0;
            pack_ = null;
            onChanged();
          }
        } else {
          if (packCase_ == 2) {
            packCase_ = 0;
            pack_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public netty.sixexample.MyDataInfo.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      public netty.sixexample.MyDataInfo.StudentOrBuilder getStudentOrBuilder() {
        if ((packCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (packCase_ == 2) {
            return (netty.sixexample.MyDataInfo.Student) pack_;
          }
          return netty.sixexample.MyDataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.text.protobuf.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          netty.sixexample.MyDataInfo.Student, netty.sixexample.MyDataInfo.Student.Builder, netty.sixexample.MyDataInfo.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(packCase_ == 2)) {
            pack_ = netty.sixexample.MyDataInfo.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              netty.sixexample.MyDataInfo.Student, netty.sixexample.MyDataInfo.Student.Builder, netty.sixexample.MyDataInfo.StudentOrBuilder>(
                  (netty.sixexample.MyDataInfo.Student) pack_,
                  getParentForChildren(),
                  isClean());
          pack_ = null;
        }
        packCase_ = 2;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          netty.sixexample.MyDataInfo.Number, netty.sixexample.MyDataInfo.Number.Builder, netty.sixexample.MyDataInfo.NumberOrBuilder> numberBuilder_;
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public boolean hasNumber() {
        return packCase_ == 3;
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public netty.sixexample.MyDataInfo.Number getNumber() {
        if (numberBuilder_ == null) {
          if (packCase_ == 3) {
            return (netty.sixexample.MyDataInfo.Number) pack_;
          }
          return netty.sixexample.MyDataInfo.Number.getDefaultInstance();
        } else {
          if (packCase_ == 3) {
            return numberBuilder_.getMessage();
          }
          return netty.sixexample.MyDataInfo.Number.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public Builder setNumber(netty.sixexample.MyDataInfo.Number value) {
        if (numberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pack_ = value;
          onChanged();
        } else {
          numberBuilder_.setMessage(value);
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public Builder setNumber(
          netty.sixexample.MyDataInfo.Number.Builder builderForValue) {
        if (numberBuilder_ == null) {
          pack_ = builderForValue.build();
          onChanged();
        } else {
          numberBuilder_.setMessage(builderForValue.build());
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public Builder mergeNumber(netty.sixexample.MyDataInfo.Number value) {
        if (numberBuilder_ == null) {
          if (packCase_ == 3 &&
              pack_ != netty.sixexample.MyDataInfo.Number.getDefaultInstance()) {
            pack_ = netty.sixexample.MyDataInfo.Number.newBuilder((netty.sixexample.MyDataInfo.Number) pack_)
                .mergeFrom(value).buildPartial();
          } else {
            pack_ = value;
          }
          onChanged();
        } else {
          if (packCase_ == 3) {
            numberBuilder_.mergeFrom(value);
          }
          numberBuilder_.setMessage(value);
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public Builder clearNumber() {
        if (numberBuilder_ == null) {
          if (packCase_ == 3) {
            packCase_ = 0;
            pack_ = null;
            onChanged();
          }
        } else {
          if (packCase_ == 3) {
            packCase_ = 0;
            pack_ = null;
          }
          numberBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public netty.sixexample.MyDataInfo.Number.Builder getNumberBuilder() {
        return getNumberFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      public netty.sixexample.MyDataInfo.NumberOrBuilder getNumberOrBuilder() {
        if ((packCase_ == 3) && (numberBuilder_ != null)) {
          return numberBuilder_.getMessageOrBuilder();
        } else {
          if (packCase_ == 3) {
            return (netty.sixexample.MyDataInfo.Number) pack_;
          }
          return netty.sixexample.MyDataInfo.Number.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.text.protobuf.Number number = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          netty.sixexample.MyDataInfo.Number, netty.sixexample.MyDataInfo.Number.Builder, netty.sixexample.MyDataInfo.NumberOrBuilder> 
          getNumberFieldBuilder() {
        if (numberBuilder_ == null) {
          if (!(packCase_ == 3)) {
            pack_ = netty.sixexample.MyDataInfo.Number.getDefaultInstance();
          }
          numberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              netty.sixexample.MyDataInfo.Number, netty.sixexample.MyDataInfo.Number.Builder, netty.sixexample.MyDataInfo.NumberOrBuilder>(
                  (netty.sixexample.MyDataInfo.Number) pack_,
                  getParentForChildren(),
                  isClean());
          pack_ = null;
        }
        packCase_ = 3;
        onChanged();;
        return numberBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.text.protobuf.Pack)
    }

    // @@protoc_insertion_point(class_scope:com.text.protobuf.Pack)
    private static final netty.sixexample.MyDataInfo.Pack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netty.sixexample.MyDataInfo.Pack();
    }

    public static netty.sixexample.MyDataInfo.Pack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Pack>
        PARSER = new com.google.protobuf.AbstractParser<Pack>() {
      @java.lang.Override
      public Pack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public netty.sixexample.MyDataInfo.Pack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.text.protobuf.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.text.protobuf.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.text.protobuf.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netty.sixexample.MyDataInfo.Student.class, netty.sixexample.MyDataInfo.Student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netty.sixexample.MyDataInfo.Student)) {
        return super.equals(obj);
      }
      netty.sixexample.MyDataInfo.Student other = (netty.sixexample.MyDataInfo.Student) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netty.sixexample.MyDataInfo.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netty.sixexample.MyDataInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.text.protobuf.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.text.protobuf.Student)
        netty.sixexample.MyDataInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netty.sixexample.MyDataInfo.Student.class, netty.sixexample.MyDataInfo.Student.Builder.class);
      }

      // Construct using netty.sixexample.MyDataInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Student_descriptor;
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Student getDefaultInstanceForType() {
        return netty.sixexample.MyDataInfo.Student.getDefaultInstance();
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Student build() {
        netty.sixexample.MyDataInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Student buildPartial() {
        netty.sixexample.MyDataInfo.Student result = new netty.sixexample.MyDataInfo.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netty.sixexample.MyDataInfo.Student) {
          return mergeFrom((netty.sixexample.MyDataInfo.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netty.sixexample.MyDataInfo.Student other) {
        if (other == netty.sixexample.MyDataInfo.Student.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netty.sixexample.MyDataInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netty.sixexample.MyDataInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.text.protobuf.Student)
    }

    // @@protoc_insertion_point(class_scope:com.text.protobuf.Student)
    private static final netty.sixexample.MyDataInfo.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netty.sixexample.MyDataInfo.Student();
    }

    public static netty.sixexample.MyDataInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public netty.sixexample.MyDataInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.text.protobuf.Number)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.text.protobuf.Number}
   */
  public  static final class Number extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.text.protobuf.Number)
      NumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Number.newBuilder() to construct.
    private Number(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Number() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Number(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Number_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Number_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netty.sixexample.MyDataInfo.Number.class, netty.sixexample.MyDataInfo.Number.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netty.sixexample.MyDataInfo.Number)) {
        return super.equals(obj);
      }
      netty.sixexample.MyDataInfo.Number other = (netty.sixexample.MyDataInfo.Number) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netty.sixexample.MyDataInfo.Number parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Number parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Number parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.sixexample.MyDataInfo.Number parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netty.sixexample.MyDataInfo.Number prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.text.protobuf.Number}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.text.protobuf.Number)
        netty.sixexample.MyDataInfo.NumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Number_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Number_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netty.sixexample.MyDataInfo.Number.class, netty.sixexample.MyDataInfo.Number.Builder.class);
      }

      // Construct using netty.sixexample.MyDataInfo.Number.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netty.sixexample.MyDataInfo.internal_static_com_text_protobuf_Number_descriptor;
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Number getDefaultInstanceForType() {
        return netty.sixexample.MyDataInfo.Number.getDefaultInstance();
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Number build() {
        netty.sixexample.MyDataInfo.Number result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public netty.sixexample.MyDataInfo.Number buildPartial() {
        netty.sixexample.MyDataInfo.Number result = new netty.sixexample.MyDataInfo.Number(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netty.sixexample.MyDataInfo.Number) {
          return mergeFrom((netty.sixexample.MyDataInfo.Number)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netty.sixexample.MyDataInfo.Number other) {
        if (other == netty.sixexample.MyDataInfo.Number.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netty.sixexample.MyDataInfo.Number parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netty.sixexample.MyDataInfo.Number) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.text.protobuf.Number)
    }

    // @@protoc_insertion_point(class_scope:com.text.protobuf.Number)
    private static final netty.sixexample.MyDataInfo.Number DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netty.sixexample.MyDataInfo.Number();
    }

    public static netty.sixexample.MyDataInfo.Number getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Number>
        PARSER = new com.google.protobuf.AbstractParser<Number>() {
      @java.lang.Override
      public Number parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Number(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Number> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Number> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public netty.sixexample.MyDataInfo.Number getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_text_protobuf_Pack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_text_protobuf_Pack_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_text_protobuf_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_text_protobuf_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_text_protobuf_Number_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_text_protobuf_Number_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/protobuf/Student.proto\022\021com.text.p" +
      "rotobuf\"\231\001\n\004Pack\022-\n\010packType\030\001 \002(\0162\033.com" +
      ".text.protobuf.PackType\022-\n\007student\030\002 \001(\013" +
      "2\032.com.text.protobuf.StudentH\000\022+\n\006number" +
      "\030\003 \001(\0132\031.com.text.protobuf.NumberH\000B\006\n\004P" +
      "ack\"5\n\007Student\022\014\n\004name\030\001 \002(\t\022\013\n\003age\030\002 \001(" +
      "\005\022\017\n\007address\030\003 \001(\t\"#\n\006Number\022\n\n\002id\030\001 \002(\005" +
      "\022\r\n\005value\030\002 \001(\t*#\n\010PackType\022\013\n\007STUDENT\020\000" +
      "\022\n\n\006NUMBER\020\001B \n\020netty.sixexampleB\nMyData" +
      "InfoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_text_protobuf_Pack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_text_protobuf_Pack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_text_protobuf_Pack_descriptor,
        new java.lang.String[] { "PackType", "Student", "Number", "Pack", });
    internal_static_com_text_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_text_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_text_protobuf_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_com_text_protobuf_Number_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_text_protobuf_Number_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_text_protobuf_Number_descriptor,
        new java.lang.String[] { "Id", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
